### PR TITLE
Solves https://github.com/sidorares/pugify/issues/39

### PR DESCRIPTION
**Pull request by hawkerboy7**

### CODE REVIEW

**Comment by sidorares** [comment]
thanks!

**Comment by hawkerboy7** [comment]
No problem! When will you publish a new version containing this change on npm? I'd like to `npm install pugify` which includes this fix ;)

**Comment by sidorares** [comment]
done, v2.2.0

**Comment by hawkerboy7** [comment]
My Hero! Thx =D

**Pull request merged**
